### PR TITLE
Changing login dialog for better readability

### PR DESCRIPTION
**Pull request by silversword411**
Description:
Updating changes as discussed here: https://sqrl.grc.com/threads/improve-readability-of-wp-login-dialog.1057/#post-9014

Changes:
Separating SQRL login from WP login with border, adding logo and rearranging and formatting items.

### CODE REVIEW

**Comment by sanzeeb3** [comment]
@silversword411 be sure to make all the strings translatable.

**Comment by silversword411** [comment]
...I only added two titles "scan" and "or click". 

How would I do that?

**Comment by sanzeeb3** [comment]
@silversword411 yeah that. there are many in the codes, example: `esc_html__( 'Associate with account', 'sqrl' );`

**Comment by kalaspuffar** [comment]
Hi @silversword411 

Please look at the issues reported in the continuous integration pipeline. Some are due to styling issues others make some of the unit tests fail.

Best regards
Daniel

**Comment by silversword411** [comment]
@kalaspuffar 

After 10mins I finally figured out this is the error summary, not the red parts of the of the test page:

```
FOUND 13 ERRORS AND 6 WARNINGS AFFECTING 14 LINES
--------------------------------------------------------------------------------
 552 | ERROR   | [x] Expected 1 spaces after opening bracket; 0 found
 552 | ERROR   | [x] Expected 1 spaces before closing bracket; 0 found
 554 | WARNING | [ ] Found precision alignment of 1 spaces.
 561 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 562 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 563 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 564 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 565 | ERROR   | [x] Tabs must be used to indent lines; spaces are not allowed
 580 | WARNING | [ ] Found precision alignment of 3 spaces.
 581 | WARNING | [ ] Found precision alignment of 3 spaces.
 581 | ERROR   | [x] Expected 1 spaces after opening bracket; 0 found
 581 | ERROR   | [x] Expected 1 spaces before closing bracket; 0 found
 582 | WARNING | [ ] Found precision alignment of 3 spaces.
 583 | WARNING | [ ] Found precision alignment of 3 spaces.
 592 | ERROR   | [x] Expected 1 spaces after opening bracket; 0 found
 592 | ERROR   | [x] Expected 1 spaces before closing bracket; 0 found
 595 | ERROR   | [x] Expected 1 spaces after opening bracket; 0 found
 595 | ERROR   | [x] Expected 1 spaces before closing bracket; 0 found
 902 | WARNING | [x] Equals sign not aligned with surrounding assignments;
     |         |     expected 6 spaces but found 1 space
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 14 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

I didn't even change line 902.

I tried looking up how "PHPCBF CAN FIX" but the only things I found were Mac systems with an entire build system installed with php and running code. I don't have a build system with php running somewhere and can't execute the clean command. I literally manually made the php edits in the respective wordpress plugin editor, then copied those to a code formatter online, and then pasted the cleaned code to the github text editor.

Maybe someone else can help with these formatting warnings and fix the esc_html__ issue as well. I think my coding skills have been exceeded at this point. :(

**Comment by kalaspuffar** [comment]
Hi @silversword411 

I've now created #60 which builds on this one. Could you review it and see if you're changes are still there. The tests now pass and all style issues have been resolved.

Best regards
Daniel

**Comment by silversword411** [comment]
@kalaspuffar I copied and pasted the php and css into my wordpress, and everything looks right in the end :)

**Pull request merged**
